Mozu/MozuAndroidInStoreAssistant

MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/ChooseTenantAndSiteActivity.java, MozuAndroidInStoreAssistant/app/src/main/res/values/strings.xml, MozuAndroidInStoreAssistant/app/src/main/res/values/styles_mozu.xml
user without tenants sees prompt and is returned to the login screen
added alert dialog style
=> no tenants fix

MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/product/ProductDetailOverviewFragment.java
=> Fix Map price

MozuAndroidInStoreAssistant/app/build.gradle
added android.volusion to distribution list.
=> added android.volusion

MozuAndroidInStoreAssistant/app/build.gradle, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/OrderDetailActivity.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/bus/RxBus.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/NewOrderActivity.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/OrderDetailNotesFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/OrderNotesUpdateListener.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/adapters/NewOrderFragmentAdapter.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/adapters/OrderDetailNotesAdapter.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/adapters/OrderDetailSectionPagerAdapter.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/loaders/OrderNoteObserverable.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/tasks/CustomerAsyncListener.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/tasks/RetrieveCustomerAsyncTask.java, MozuAndroidInStoreAssistant/app/src/main/res/layout/activity_order_detail.xml, MozuAndroidInStoreAssistant/app/src/main/res/layout/dialog_edit_order_notes.xml, MozuAndroidInStoreAssistant/app/src/main/res/layout/order_detail_notes_fragment.xml, MozuAndroidInStoreAssistant/app/src/main/res/values/strings.xml
added order note creation / update / delete
added edit mode for order details
=> Order creation notes

MozuAndroidInStoreAssistant/app/src/main/AndroidManifest.xml, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/CustomerCreationActivity.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/CustomerLookUpActivity.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/MainActivity.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/OrderCreationAddCustomerActivity.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerAddAddressFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerAddressFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerAddressOrderVerification.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerCreationFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerCreationListener.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerLookupFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/CreateOrderListener.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/NewOrderActivity.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/OrderFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/loaders/NewOrderManager.java, MozuAndroidInStoreAssistant/app/src/main/res/layout/activity_order_create.xml, MozuAndroidInStoreAssistant/app/src/main/res/layout/activity_verify_order_creation.xml, MozuAndroidInStoreAssistant/app/src/main/res/layout/customer_address_layout.xml, MozuAndroidInStoreAssistant/app/src/main/res/layout/fragment_create_customer.xml, MozuAndroidInStoreAssistant/app/src/main/res/layout/fragment_customer_lookup.xml, MozuAndroidInStoreAssistant/app/src/main/res/values/strings.xml, MozuAndroidInStoreAssistant/app/src/main/res/values/styles_mozu.xml
can add exiting customer to order
can add new customer to order
=> Customer creation fixes

MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/OrderDetailActivity.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/bus/RxBus.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/OrderDetailNotesFragment.java
changed observerables to use AndroidObserverable
=> changed rx bus to singleton.

MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/OrderCreationAddCustomerActivity.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/bus/RxBus.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerAddressOrderVerification.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerAddressVerifier.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerCreationFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerCreationInterface.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerCreationListener.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerLookupFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/adapters/CustomerAddressesAdapter.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/adapters/CustomerLookupAdapter.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/loaders/AddCustomerContactObserverable.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/loaders/CustomerAccountCreationObserver.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/loaders/CustomerAddressValidation.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/dialog/ErrorMessageAlertDialog.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/CreateOrderListener.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/OrderFilterDialogFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/OrderFilterListener.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/OrderNotesUpdateListener.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/loaders/OrderCreateLoader.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/loaders/OrderNoteObserverable.java, MozuAndroidInStoreAssistant/app/src/main/res/layout/activity_verify_order_creation.xml, MozuAndroidInStoreAssistant/app/src/main/res/layout/fragment_customer_lookup.xml
ui fixes
npe after rotation fixes.
=> Customer selection fix

MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/OrderDetailNotesFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/adapters/OrderDetailNotesAdapter.java
Customer notes were showing if the note was null.
=> Bugfix #43615

MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/adapters/OrderDetailNotesAdapter.java, MozuAndroidInStoreAssistant/app/src/main/res/layout/notes_list_item.xml, MozuAndroidInStoreAssistant/app/src/main/res/layout/order_detail_notes_fragment.xml
removed employee column for internal notes
=> Bugfix #434416

MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerAddAddressFragment.java
reference was to the subscriber and not the fragment.
=> could not create a new customer

MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/OrderDetailActivity.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/OrderDetailFullfillmentFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/OrderFulfillmentMoveToPickupDialogFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/PickupInfoDialogFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/adapters/OrderDetailFullfillmentAdapter.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/adapters/OrderDetailSectionPagerAdapter.java, MozuAndroidInStoreAssistant/app/src/main/res/layout/fulfillment_pickup_item.xml, MozuAndroidInStoreAssistant/app/src/main/res/values/strings.xml
added header row for shipping items
showing details onClick for all rows
fragment reloads with onRefresh
=> Bugfix 44583 44545 44542

MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomersFragment.java, MozuAndroidInStoreAssistant/app/src/main/res/layout/fragment_customer.xml
not showing no results msg for customer search if there is only 1 or less.
=> bug fix 43915

MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerAddAddressFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerCreationFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/adapters/CustomerAddressesAdapter.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/OrderDetailFulfillmentFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/OrderFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/adapters/OrderDetailSectionPagerAdapter.java, MozuAndroidInStoreAssistant/app/src/main/res/layout/fragment_customer_add_address.xml, MozuAndroidInStoreAssistant/app/src/main/res/layout/item_address_card.xml, MozuAndroidInStoreAssistant/app/src/main/res/values/strings.xml
can clear filter
filter options remain
can change ascending and descending with filter options remaining
various other fixes.
=> Filter order fixes

MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/OrderCreationAddCustomerActivity.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerAddAddressFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerCreationFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerLookupFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/adapters/CustomerAddressesAdapter.java, MozuAndroidInStoreAssistant/app/src/main/res/layout/fragment_customer_add_address.xml, MozuAndroidInStoreAssistant/app/src/main/res/layout/fragment_customer_lookup.xml, MozuAndroidInStoreAssistant/app/src/main/res/values/strings.xml
added spinner for customer lookup
can delete correct items
reorder to show defaults first.
=> bug fixes and layout changes

MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerAddAddressFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerCreationFragment.java, MozuAndroidInStoreAssistant/app/src/main/res/layout/item_address_card.xml
ui updates
can only select 1 default bill/shipping item
=> fixes for default billing/shipping address

MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/MozuApplication.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/CustomerUpdateActivity.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/MainActivity.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/OrderCreationAddCustomerActivity.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/OrdersInStoreFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerLookupFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/loaders/CustomersLoader.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/adapters/OrderInStoreLookupAdapter.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/loaders/OrdersLoader.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/settings/SettingsFragment.java, MozuAndroidInStoreAssistant/app/src/main/res/layout-land/activity_order_detail.xml, MozuAndroidInStoreAssistant/app/src/main/res/layout/activity_order_detail.xml, MozuAndroidInStoreAssistant/app/src/main/res/layout/lookup_item.xml, MozuAndroidInStoreAssistant/app/src/main/res/layout/order_lookup_item.xml, MozuAndroidInStoreAssistant/app/src/main/res/layout/orders_instore_mode.xml, MozuAndroidInStoreAssistant/app/src/main/res/layout/settings_fragment_layout.xml, MozuAndroidInStoreAssistant/app/src/main/res/values/strings.xml
added instore mode lookup for order and customer
=> Instore Mode changes

MozuAndroidInStoreAssistant/app/src/main/res/layout/payment_list_item.xml
Add layout changes  for portrait as well
=> add payment item layout for portrait mode

MozuAndroidInStoreAssistant/app/src/main/AndroidManifest.xml, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/LoginActivity.java
=> login fixes. input remains on rotation. keyboard doesn't open everytime

MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/OrderDetailNotesFragment.java
no customer notes hint centers
=> 45044 bugfix revision

MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/OrderDetailActivity.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/OrderDetailNotesFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/utils/ContactIntentUtil.java, MozuAndroidInStoreAssistant/app/src/main/res/layout/notes_list_item.xml, MozuAndroidInStoreAssistant/app/src/main/res/values/strings.xml
email in order detail can be clicked to open an email client (45043)
text color is dark black when there is a note
=> Active email and notes color

MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerAddAddressFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/layout/order/NewOrderTotalLayout.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/utils/CustomerUtils.java, MozuAndroidInStoreAssistant/app/src/main/res/layout/new_order_product_item.xml, MozuAndroidInStoreAssistant/app/src/main/res/layout/neworder_header_layout.xml
validating customer data
phone number check was invalid
=> Validating customer address has defaults and phone numbers

MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/utils/CustomerUtils.java
if statement parenthesis was incorrect
=> npe exception in method possible

MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/layout/order/NewOrderTotalLayout.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/NewOrderCreateFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/NewOrderItemEditFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/product/ProductDetailOverviewFragment.java, MozuAndroidInStoreAssistant/app/src/main/res/layout/neworder_item_edit_fragment.xml, MozuAndroidInStoreAssistant/app/src/main/res/layout/product_detail_overview_fragment.xml
2. FIx bug with save button not showing up
3. Refresh order on item edit
=> 1. Add strike through for sale price

MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerAddAddressFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerCreationFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/loaders/AddCustomerContactObservable.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/layout/customer/CustomerAccountInfoHeader.java, MozuAndroidInStoreAssistant/app/src/main/res/values/strings.xml
keep address id when editing
address sort in a fixed manner
customer email clickable
=> Various fixes for add address

MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/CustomerUpdateActivity.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/OrderCreationAddCustomerActivity.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerAddAddressFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerLookupFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/adapters/CustomerAddressesAdapter.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/loaders/CustomerManager.java, MozuAndroidInStoreAssistant/app/src/main/res/values/strings.xml
search text remains
do not delete customer address until service completes
added constant
=> can delete existing customer address

MozuAndroidInStoreAssistant/app/build.gradle
=> Release v2.0 -DEV

MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerAddAddressFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerCreationFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/NewOrderActivity.java
fixed crash based on using bound view before Butterknife.bind
save phone to home and mobile.
=> Bugfix 46616 | Creating new order crash

MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/CreateOrderTask.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/OrderCreationAddCustomerActivity.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerAddAddressFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/customer/CustomerLookupFragment.java, MozuAndroidInStoreAssistant/app/src/main/java/com/mozu/mozuandroidinstoreassistant/app/order/loaders/NewOrderManager.java
=> switched create order to async task
